### ISSUE TITLE
Contains reserved characters

### ISSUE THREAD

**Issue by omerkoseoglu** [dominikb/composer-license-checker#28]
Hi,

When I run it with the report parameter, I get the following error.

```
Looking up https://github.com/paypal/Checkout-PHP-SDK/blob/master/LICENSE ...

In CacheItem.php line 167:

  Cache key "https://github.com/paypal/Checkout-PHP-SDK/blob/master/LICENSE" contains reserved characters "{}()/\@:".
```

**Comment by dominikb** [comment]
I've looked into it and know what the issue is. 

This package depends on the `composer licenses` command that reports entries in the `composer.json` file. The `paypal/checkout-php-sdk` in version 1.0.2 just [points to a local file](https://github.com/paypal/Checkout-PHP-SDK/blob/19992ce7051ff9e47e643f28abb8cc1b3e5f1812/composer.json#L6). A [commit fixing this](https://github.com/paypal/Checkout-PHP-SDK/commit/d004c72c2eb16ad16ffe96ceda708007d599a584) was made on the same day but did not make it into a package release.

An immediate fix could be to upgrade the package to this specific commit. As it is archived anyway, I don't expect any new versions and this shouldn't be too much of a problem. Can be done using `composer require paypal/paypal-checkout-sdk dev-master#19992ce7051ff9e47e643f28abb8cc1b3e5f1812`.

I'll fix the bug in this repository where the raw license name was used as a cache key (instead of a hash). This will get rid of the error but the reported license would still be incorrect (as it would not look up Apache-2).
